version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend_fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://22050040_db_user:Accnam55@giasanpham.uqyaw1p.mongodb.net/?appName=GiaSanPham
      - MONGO_DB=price_tracker

  frontend:
    image: nginx:alpine
    container_name: frontend_dashboard
    ports:
      - "3000:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html