import os

lines = []
lines.append('# -*- coding: utf-8 -*-')
lines.append('"""')
lines.append('Comment Scraper cho 8 sàn thương mại điện tử.')
lines.append('"""')
lines.append('import os')
lines.append('import sys')
lines.append('import re')
lines.append('import asyncio')
lines.append('import random')
lines.append('import logging')
lines.append('from datetime import datetime, timezone')
lines.append('from typing import Any, Dict, List, Optional')
lines.append('')
lines.append('if hasattr(sys.stdout, \"reconfigure\"):')
lines.append('    sys.stdout.reconfigure(encoding=\"utf-8\", errors=\"replace\")')
lines.append('    sys.stderr.reconfigure(encoding=\"utf-8\", errors=\"replace\")')
lines.append('')
lines.append('from pymongo import MongoClient')
lines.append('from bs4 import BeautifulSoup')
lines.append('import aiohttp')
lines.append('')
lines.append('logging.basicConfig(')
lines.append('    level=logging.INFO,')
lines.append('    format="%(asctime)s [%(levelname)s] %(message)s",')
lines.append('    datefmt="%Y-%m-%d %H:%M:%S"')
lines.append(')')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('MONGO_URI = os.environ.get(')
lines.append('    "MONGO_URI",')
lines.append('    "mongodb+srv://22050040_db_user:Accnam55@giasanpham.uqyaw1p.mongodb.net/?appName=GiaSanPham"')
lines.append(')')
lines.append('MONGO_DB = os.environ.get("MONGO_DB", "price_tracker")')
lines.append('')
lines.append('STORE_COLLECTIONS = {')
lines.append('    "FPT Shop": "fpt",')
lines.append('    "Thế Giới Di Động": "tgdd",')
lines.append('    "CellphoneS": "cellphones",')
lines.append('    "Hoàng Hà Mobile": "hoangha",')
lines.append('    "Di Động Việt": "didongviet",')
lines.append('    "Viettel Store": "viettelstore",')
lines.append('    "Clickbuy": "clickbuy",')
lines.append('    "MobileCity": "mobilecity",')
lines.append('}')
lines.append('')
lines.append('USER_AGENTS = [')
lines.append('    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",')
lines.append('    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",')
lines.append(']')
lines.append('')
lines.append('async def fetch_page(session, url, timeout=15):')
lines.append('    try:')
lines.append('        headers = {"User-Agent": random.choice(USER_AGENTS), "Accept": "text/html"}')
lines.append('        async with session.get(url, headers=headers, timeout=aiohttp.ClientTimeout(total=timeout)) as resp:')
lines.append('            if resp.status == 200:')
lines.append('                text = await resp.text()')
lines.append('                if text and len(text) > 500:')
lines.append('                    return text')
lines.append('    except Exception as e:')
lines.append('        logger.debug(f"Fetch error: {e}")')
lines.append('    return None')

with open('scrapers/comment_scraper.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print('Part 1 written')
